// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuvvwmwoscqaejpaensb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1dnZ3bXdvc2NxYWVqcGFlbnNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NDM0MzcsImV4cCI6MjA3MTExOTQzN30.j4pj7r4vXh1-4wdVF1gGxW0W7sjPv48qQsBkRshPoEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});